from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import HTMLResponse, JSONResponse
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from sqlalchemy.orm import selectinload

from aitester.db.models.test_run import TestRun
from aitester.db.session import get_db
from aitester.reports.html_generator import generate_html_report
from aitester.reports.json_generator import generate_json_report

router = APIRouter(prefix="/runs/{run_id}/report", tags=["Reports"])

async def _get_run_data(run_id: str, db: AsyncSession) -> dict:
    stmt = select(TestRun).options(
        selectinload(TestRun.test_cases).selectinload(TestRun.test_cases.property.mapper.class_.test_results)
    ).filter(TestRun.id == run_id)

    result = await db.execute(stmt)
    test_run = result.scalar_one_or_none()

    if not test_run:
        raise HTTPException(status_code=404, detail=f"Test run {run_id} not found")

    results_data = []
    for tc in test_run.test_cases:
        for tr in tc.test_results:
            results_data.append({
                "test_case_name": tc.category + " - " + tc.endpoint,
                "category": tc.category,
                "status": tr.status,
                "method": tc.method,
                "path": tc.endpoint,
                "actual_status_code": tr.actual_status_code,
                "response_time_ms": tr.response_time_ms,
            })

    return {
        "project_name": "API Project",
        "run_id": str(test_run.id),
        "started_at": test_run.started_at.isoformat() if test_run.started_at else None,
        "completed_at": test_run.completed_at.isoformat() if test_run.completed_at else None,
        "duration_ms": 0,
        "results": results_data,
        "security_score": 100.0,
        "security_findings": [],
        "ai_executive_summary": "Report generated by AITester API."
    }

@router.get("/html", response_class=HTMLResponse)
async def get_html_report(run_id: str, db: AsyncSession = Depends(get_db)):
    """Get the HTML report for a test run."""
    run_data = await _get_run_data(run_id, db)
    html_content = generate_html_report(run_data)
    return HTMLResponse(content=html_content)

@router.get("/json", response_class=JSONResponse)
async def get_json_report(run_id: str, db: AsyncSession = Depends(get_db)):
    """Get the JSON report for a test run."""
    run_data = await _get_run_data(run_id, db)
    # generate_json_report returns a string, but JSONResponse expects a dict
    # We can either parse the string back or just build it.
    import json
    json_content = generate_json_report(run_data)
    return JSONResponse(content=json.loads(json_content))
