"""Initial schema

Revision ID: 2f46f9030cc0
Revises: 
Create Date: 2026-06-15 11:33:47.260405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f46f9030cc0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('openapi_spec', sa.JSON(), nullable=True, comment='Parsed OpenAPI Spec as JSON'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_run_id', sa.UUID(), nullable=False),
    sa.Column('total_tests', sa.Integer(), nullable=False),
    sa.Column('passed_tests', sa.Integer(), nullable=False),
    sa.Column('failed_tests', sa.Integer(), nullable=False),
    sa.Column('html_report_path', sa.String(length=1024), nullable=True),
    sa.Column('json_report_path', sa.String(length=1024), nullable=True),
    sa.Column('security_score', sa.Float(), nullable=False),
    sa.Column('ai_executive_summary', sa.JSON(), nullable=True, comment='AI-generated high-level summary of the run'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_run_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False, comment='FUNCTIONAL, EDGE, AI, SECURITY'),
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('query_params', sa.JSON(), nullable=True),
    sa.Column('body', sa.JSON(), nullable=True),
    sa.Column('expected_status_code', sa.Integer(), nullable=True),
    sa.Column('expected_schema', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_run_id', sa.UUID(), nullable=False),
    sa.Column('test_case_id', sa.UUID(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('actual_status_code', sa.Integer(), nullable=True),
    sa.Column('actual_body', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('ai_failure_analysis', sa.JSON(), nullable=True, comment='Structured failure reason from Gemini'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_results')
    op.drop_table('test_cases')
    op.drop_table('reports')
    op.drop_table('test_runs')
    op.drop_table('projects')
    # ### end Alembic commands ###
