import typer
import asyncio
from rich.console import Console
from rich.panel import Panel
from typing import Optional

from aitester.reports.json_generator import generate_json_report
from aitester.reports.html_generator import generate_html_report
from aitester.db.session import AsyncSessionLocal
from aitester.db.models.test_run import TestRun
from sqlalchemy.orm import selectinload
from sqlalchemy.future import select

console = Console()

def report(
    run_id: str = typer.Argument(..., help="The ID of the test run"),
    fmt: str = typer.Option("html", "--format", "-f", help="Output format (html/json)"),
    output: Optional[str] = typer.Option(None, "--output", "-o", help="Output file path")
):
    """
    Generate a beautiful HTML or JSON report for a test run.
    """
    asyncio.run(_generate_report(run_id, fmt, output))

async def _generate_report(run_id: str, fmt: str, output: Optional[str]):
    console.print(f"[bold cyan]Generating {fmt.upper()} report for run: {run_id}[/bold cyan]")
    
    async with AsyncSessionLocal() as db:
        stmt = select(TestRun).options(
            selectinload(TestRun.test_cases).selectinload(TestRun.test_cases.property.mapper.class_.test_results)
        ).filter(TestRun.id == run_id)
        
        result = await db.execute(stmt)
        test_run = result.scalar_one_or_none()
        
        if not test_run:
            console.print(f"[bold red]Error: Test run {run_id} not found in database.[/bold red]")
            raise typer.Exit(code=1)
            
        results_data = []
        for tc in test_run.test_cases:
            for tr in tc.test_results:
                results_data.append({
                    "test_case_name": tc.name if hasattr(tc, "name") else f"{tc.category} - {tc.endpoint}",
                    "category": tc.category,
                    "status": tr.status,
                    "method": tc.method,
                    "path": tc.endpoint,
                    "actual_status_code": tr.actual_status_code,
                    "response_time_ms": tr.response_time_ms,
                })
                
        run_data = {
            "project_name": "API Testing Platform",
            "run_id": str(test_run.id),
            "started_at": test_run.started_at.isoformat() if test_run.started_at else None,
            "completed_at": test_run.completed_at.isoformat() if test_run.completed_at else None,
            "duration_ms": 0,
            "results": results_data,
            "security_score": getattr(test_run, "security_score", 100.0),
            "security_findings": [],
            "ai_executive_summary": "Automated report generated by AITester."
        }
        
        if fmt.lower() == "html":
            content = generate_html_report(run_data)
            ext = ".html"
        else:
            content = generate_json_report(run_data)
            ext = ".json"
            
        out_path = output or f"report_{run_id}{ext}"
        
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(content)
            
        console.print(Panel(f"[bold green]Report saved to:[/bold green] {out_path}"))
